version: 1.0
services:
    runtime: java17
    build:
        commands:
            - ./gradlew clean build
        start-command: java -jar build/libs/U-Tracker_API-0.0.1-SNAPSHOT-plain.jar
    port: 8080
